### ISSUE TITLE
TypeError: unhashable type: 'GenomicFeature'

### ISSUE THREAD

**Issue by marijazmf** [roryk/DEXSeq#1]
Hi,
I tried to use dexseq_count.py for quantification, but I got error message:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "dexseq_count.py", line 105, in 
    features[f.iv] += f
  File "python3/src/HTSeq/_HTSeq.pyx", line 451, in HTSeq._HTSeq.ChromVector.__iadd__
  File "python3/src/HTSeq/_HTSeq.pyx", line 466, in HTSeq._HTSeq.ChromVector.apply
  File "python3/src/HTSeq/_HTSeq.pyx", line 449, in HTSeq._HTSeq.ChromVector.__iadd__.addval
TypeError: unhashable type: 'GenomicFeature'
```
Some idea what could be wrong?

Best,
Marija

**Comment by roryk** [comment]
Hi Marija,

It's probably good to ask on the official repo, this is just a random fork I made of it, I don't have anything to do with DEXSeq: http://bioconductor.org/packages/release/bioc/html/DEXSeq.html
